<?php
define('TBL_JOB_CATEGORY','job_category');
define('TBL_JOB_TYPE','job_type');
define('TBL_JOB_POST','jobs');
define('TBL_JOB_TO_CATEGORY','job_to_category');
define('TBL_JOB_TO_ATTACHMENT','job_to_attachment');
define('TBL_USER','users');
define('TBL_PACKAGE','package');
define('TBL_USER_TO_PORTFOLIO','users_to_portfolio');
define('TBL_USER_TO_LOGO','users_to_logo');
define('TBL_JOB_INVITATION','job_invitation');
define('TBL_REVIEW','review');
?>