<?php
define('TBL_JOB_CATEGORY','job_category');
define('TBL_JOB_TYPE','job_type');
define('TBL_JOB_POST','jobs');
define('TBL_JOB_TO_CATEGORY','job_to_category');
define('TBL_JOB_TO_ATTACHMENT','job_to_attachment');
define('TBL_USER','users');
define('TBL_PACKAGE','package');
?>